name: Nightly DB Backup

on:
  schedule:
    - cron: "0 3 * * *"   # 03:00 UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Instalar cliente PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Preparar pasta
        run: mkdir -p backups

      - name: Dump (pg_dump custom + gzip)
        env:
          DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          set -euo pipefail
          echo "::add-mask::$DB_URL"
          TS=$(date -u +"%Y-%m-%dT%H-%M-%SZ")
          FILE="db_${TS}.dump.gz"
          pg_dump --no-owner --no-acl --format=custom "$DB_URL" | gzip -c > "backups/$FILE"
          echo "FILENAME=$FILE" >> "$GITHUB_ENV"

      - name: Enviar para repositório de backups
        env:
          PAT:  ${{ secrets.BACKUP_PAT }}
          REPO: ${{ secrets.BACKUP_REPO }}
        run: |
          set -euo pipefail
          git clone "https://${PAT}@github.com/${REPO}.git" out
          mkdir -p out/pgsql
          cp -f "backups/${FILENAME}" out/pgsql/
          cd out
          git config user.name  "bidly-backup-bot"
          git config user.email "bot@users.noreply.github.com"
          git add -A
          git commit -m "backup: ${FILENAME}" || echo "Nada para commit"
          git push origin main
